### ISSUE TITLE
Does this work with Buy DRM?

### ISSUE THREAD

**Issue by sanjeevghimire** [radiantmediaplayer/rmp-cast-receiver#1]
buy drm expects customdata to be sent part of the header?  Any idea how to make this work with buy drm?

**Comment by radiantmediaplayer** [comment]
You can pass licenseCustomData in a custom CAF receiver as detailed here: https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.PlaybackConfig#licenseCustomData. We are looking to make this easier for the player to automatically send those data to the CAF receiver but right now it needs to be developed in the CAF receiver itself.

**Comment by radiantmediaplayer** [comment]
With Radiant Media Player [5.8.4](https://www.radiantmediaplayer.com/version-history.html#584) we have now release out the box support for passing DRM data from the player to the CAF receiver. See player [code example here](https://www.radiantmediaplayer.com/docs/latest/google-cast.html#drm). This should cover the BuyDRM use case as well.
