### ISSUE TITLE
Video is freezing when casting AVOD

### ISSUE THREAD

**Issue by raphaelbgr** [radiantmediaplayer/rmp-cast-receiver#2]
Hello, I'm trying to cast from an android app an AVOD video, the format is HLS via m3u8.

The webapp attempts to play the content but freezes on the Chromecast to a point that even the remote debugger does not respond, here is the video play attemp frozen. I looked already for a lot ot possibilities, but I've found nothing, other videos plays fine.

m3u8 file:
![image](https://user-images.githubusercontent.com/6786682/111512956-0f9b9800-872f-11eb-872b-c77f10ef3aef.png)

Cast attempt footage:
https://user-images.githubusercontent.com/6786682/111512667-be8ba400-872e-11eb-87d3-26d1ea687d8c.mp4

**Comment by radiantmediaplayer** [comment]
Hi,

Please open a ticket with the Cast SDK Issue Tracker https://developers.google.com/cast/support to report issue with playback on the cast receiver. 

Thanks
Arnaud
